### ISSUE TITLE
Build Failure - Compilation error in stratosphere-java

### ISSUE THREAD

**Issue by aaronchlam** [stratosphere/stratosphere#673] opened 2014-04-10 00:32 UTC
I followed instructions according to the Build from Source instruction in README.md. Encountered a compilation error at stratosphere-java.
Maven output at this link https://gist.github.com/aaronchlam/2633b99ab65a262deec7

```
Aarons-MacBook-Pro:Stratosphere aaronlam$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-462-11M4609)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-462, mixed mode)
Aarons-MacBook-Pro:Stratosphere aaronlam$ mvn -version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T12:37:52-05:00)
Maven home: /usr/local/Cellar/maven/3.2.1/libexec
Java version: 1.6.0_65, vendor: Apple Inc.
Java home: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
Default locale: en_US, platform encoding: MacRoman
OS name: "mac os x", version: "10.9.2", arch: "x86_64", family: "mac"
```

I've checked the pom.xml and the versions match:

```
<plugin>
    <!-- just define the Java version to be used for compiling and plugins -->
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.1</version>
    <configuration>
        <source>1.6</source>
        <target>1.6</target>
        <!-- High optimization, no debugging <compilerArgument>-g:none -O</compilerArgument> -->
    </configuration>
</plugin>
```

**Comment by StephanEwen** [comment] 2014-04-10 06:02
Does this occur reproducibility every time? Looks like a bug in the Java
compiler.

You can probably fix this by updating your Java version to 1.7
Unfortunately, Oracle does not provide patches for 1.6 any more.
Am 10.04.2014 02:32 schrieb "Aaron Lam" notifications@github.com:

**Comment by fhueske** [comment] 2014-04-10 08:10
Hi Aaron, 

thanks for reporting this issue!
It was identified before (#575) but unfortunately we did not update the pom files. :worried: 

Since you asked on the ML for a task to start with Stratosphere, you might want to fix the bug you caught as a first contribution. I will in the mean time update the list of starter tasks and help you to pick on.

Does that sound good to you?

**Comment by aaronchlam** [comment] 2014-04-10 12:47
@StephanEwen I reran the build and it gave the same compilation error. See gist  here https://gist.github.com/aaronchlam/379d76443e58a426a8ab#file-stratosphere_compile_failure_rerun
I cloned and ran in a separate directory and ran into the same problem. See gist here https://gist.github.com/aaronchlam/379d76443e58a426a8ab#file-stratosphere_compile_failure_clone_and_build

I'm upgrading my Java now. I will post an update.

**Comment by aaronchlam** [comment] 2014-04-10 13:35
I've updates to java 7 and updated the pom.xml

```
            <plugin>
                <!-- just define the Java version to be used for compiling and plugins -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                    <!-- High optimization, no debugging <compilerArgument>-g:none -O</compilerArgument> -->
                </configuration>
            </plugin>
            <plugin>
```

Since this is a duplicate issue, do I put the pull request on this issue or on the issue #575 ?

Also, the README.md's Build from Source Requirements currently states "Java 6 or 7". So I guess this needs to be updated too. Should I open a new issue, modify the REAMDE.md to say just Java 7 as my 2nd contribution?

**Comment by sscdotopen** [comment] 2014-04-10 13:38
Is it really necessary to already update to java7 ? If not, I'd vote for
staying at 6, because at lot people haven't updated their clusters yet to
my knowledge.
Am 10.04.2014 15:35 schrieb "Aaron Lam" notifications@github.com:

**Comment by StephanEwen** [comment] 2014-04-10 13:45
I agree, I would like to keep the pom file on Java 6. You can still use the
Java 7 compiler that fixed the bug. It will produce Java 6 compatible code
with the old pom.

**Comment by rmetzger** [comment] 2014-04-10 15:31
The problem only applies to oracle java 6, not openjdk6.
Also, many users are still at java 6. I guess there is a maven plugin to
check these versions.

Sent from my iPhone

On 10.04.2014, at 16:45, Stephan Ewen notifications@github.com wrote:

I agree, I would like to keep the pom file on Java 6. You can still use the
Java 7 compiler that fixed the bug. It will produce Java 6 compatible code
with the old pom.

## 

Reply to this email directly or view it on
GitHubhttps://github.com/stratosphere/stratosphere/issues/673#issuecomment-40082992
.

**Comment by StephanEwen** [comment] 2014-04-24 21:47
I think that we can close this issue.

This is clearly a java compiler bug in a no longer maintained version. We support Java 6 runtimes, but we support not all versions of Java 6 compilers. That affects only developers that compile the system themselves: They need to upgrade their local JDK

**Closed as completed by StephanEwen** 2014-04-24 21:47 UTC
Labels: duplicate
