### ISSUE TITLE
Current Stratosphere does not compile on Oracle JDK 6

### ISSUE THREAD

**Issue by twalthr** [stratosphere/stratosphere#575] opened 2014-03-14 11:42 UTC
When compiling Stratosphere with Oracle JDK 6 the following compiler bug occurs:

<code>
An exception has occurred in the compiler (1.6.0_26). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
java.lang.NullPointerException
    at com.sun.tools.javac.comp.Check.checkCompatibleConcretes(Check.java:1215)
    at com.sun.tools.javac.comp.Check.checkCompatibleSupertypes(Check.java:1567)
    at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:2674)
    at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:2628)
    at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:2584)
    at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:2584)
    at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:2564)
    at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1036)
    at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:765)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:730)
    at com.sun.tools.javac.main.Main.compile(Main.java:353)
    at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:115)
    at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
    at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:785)
</code>

the bug is reported here: http://bugs.java.com/view_bug.do?bug_id=6292765

OpenJDK 6 and Oracle/Open JDK 7 do not have this problem. 

Should this bug be prevented in the stratosphere code or should we don't support Oracle JDK 6 anymore?

**Comment by rmetzger** [comment] 2014-03-14 11:45
As far as I know, Oracle stopped supporting the JDK 6 in 2012.
As long as the JDK 6 is able to execute Stratosphere, we are fine.

**Comment by StephanEwen** [comment] 2014-03-15 22:57
I agree. I would not worry about this. as all newer versions work fine. It
affects only developers (who compile themselves), and those should be in a
position to upgrade a newer compiler version.

**Comment by fhueske** [comment] 2014-04-10 08:16
As found in #673, we need to update configuration of the maven-compile-plugin in the pom file to Java 1.7.

**Comment by StephanEwen** [comment] 2014-04-24 21:52
Duplicate of #673 

I am closing this for the same reason

This is clearly a java compiler bug in a no longer maintained Java version. We still support Java 6 runtimes, but we support not all versions of Java 6 compilers. That affects only developers that compile the system themselves: They need to upgrade their local JDK.

**Closed as completed by StephanEwen** 2014-04-24 21:52 UTC
Labels: bug, build system, simple-issue
