### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by physikerwelt** [stratosphere/stratosphere#148] opened 2013-10-10 17:15 UTC
The junit tests still fail.

**Comment by aljoscha** [comment] 2013-10-10 17:20
Which tests are failing?

@all Shouldn't the "mvn verify" that is run on each pull request catch them?

**Comment by rmetzger** [comment] 2013-10-10 17:24
I am aware of one unit test that contains an error. But if executed with maven surefire in the specified version (of the surefire plugin) the overall tests succeed. 

We run the integration tests using "mvn clean verify".
Please add more details on how to reproduce the error you reported.

@aljoscha: Yes, they should, but they actually don't. There is one case: If a test has an error, it is not failing. Maven (with the surefire plugin we're using) accepts errors. There is a pending pull request (https://github.com/dimalabs/ozone/pull/110) that fixes maven and the only error we're currently having. I'll most likely merge the pull request tomorrow, after discussing it with @StephanEwen.

**Comment by physikerwelt** [comment] 2013-10-10 17:32
Jenkins compiles with goal package. Feel free to take a look to the jenkins configuration. (If you are at DIMA.)

**Comment by rmetzger** [comment] 2013-10-18 14:40
I think the issue is fixed. Please reopen if not.

**Comment by physikerwelt** [comment] 2013-10-21 09:08
Unfortunately there are still many commits that lead to failing tests. It would be nice to check that before merging something to the master branch.
See
http://gerrit.formulasearchengine.com:8081/#/q/status:open,n,z
for details

**Comment by StephanEwen** [comment] 2013-10-21 09:18
Can you post specific tests and stack traces?

We have the issue that some tests become very low (almost freeze) on travis such that builds get killed and marked as broken, but that seems to be to a large extend an issue travis has with very cpu intensive tests.

Locally, tests have been running successfully for a long time now, at least on my machine, and as far as I know also for @aljoscha , @rmetzger , and @uce

**Comment by physikerwelt** [comment] 2013-10-21 09:37
Ok.
One example:
https://github.com/stratosphere/stratosphere/commit/c583dc0527a179764032558692888376202c007d
The log is quite long...
[INFO] ------------------------------------------------------------------------
[INFO] Building pact-tests 0.4-ozone-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.3:clean (default-clean) @ pact-tests ---
[INFO] Deleting file set: /var/lib/jenkins/jobs/ozone-build/workspace/pact/pact-tests/target (included: [**], excluded: [])
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven) @ pact-tests ---
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ pact-tests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /var/lib/jenkins/jobs/ozone-build/workspace/pact/pact-tests/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ pact-tests ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ pact-tests ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ pact-tests ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 129 source files to /var/lib/jenkins/jobs/ozone-build/workspace/pact/pact-tests/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /var/lib/jenkins/jobs/ozone-build/workspace/pact/pact-tests/src/test/java/eu/stratosphere/pact/test/scalaPactPrograms/EnumTrianglesOnEdgesWithDegreesITCase.java:[22,42] method getPlan in class eu.stratosphere.scala.ScalaPlanAssembler cannot be applied to given types;
  required: scala.collection.Seq<java.lang.String>
  found: java.lang.String,java.lang.String,java.lang.String,java.lang.String
  reason: actual and formal argument lists differ in length
[ERROR] /var/lib/jenkins/jobs/ozone-build/workspace/pact/pact-tests/src/test/java/eu/stratosphere/pact/test/scalaPactPrograms/ComputeEdgeDegreesITCase.java:[22,43] method getPlan in class eu.stratosphere.scala.ScalaPlanAssembler cannot be applied to given types;
  required: scala.collection.Seq<java.lang.String>
  found: java.lang.String,java.lang.String,java.lang.String,java.lang.String
  reason: actual and formal argument lists differ in length

**Comment by fhueske** [comment] 2013-10-21 09:38
For me it looks like Gerrit is also checking intermediate commits.
We only merge branches into Stratosphere master that do pass the tests. However, we do not ensure that each individual commit of a branch passes. Hence, the latest version of the main branch should pass all tests, however intermediate states might not.

I am pretty sure that my commits which Gerrit correctly marks as failing, were merged from a non-faining branch into Stratosphere master. So, I had commits with failures but these had been resolved before the branch was merged into the master branch.

**Comment by fhueske** [comment] 2013-10-21 09:40
So, the question is whether we want all commits to pass all tests or only ensure this for the latest version.

**Comment by uce** [comment] 2013-10-21 09:41
Isn't the actual stategy to squash all commits to a single one (via rebase) so that we always go from stable to stable?

Or am I misunderstanding something about the problem here? :see_no_evil:

**Comment by StephanEwen** [comment] 2013-10-21 09:42
I would suggest that we use rebase to squash issues into a single commit before merging. Ore one commit per logical unit of that issue. As such, these commits would be passing. But that is only a guideline, I would not enforce it strictly.

@physikerwelt Can you check your gerrit configuration to only test the HEAD after a version change is detected?

**Comment by fhueske** [comment] 2013-10-21 09:44
I didn't do that. That's why there were failing commits. 
But sure, that policy sounds reasonable and should be communicated. ;-)

**Comment by rmetzger** [comment] 2013-10-21 09:44
I would say no, because this would make our work quite annoying. Pull requests are our unit of work-transfer. So each pull request is a transition from a stable state to another stable state.
I don't want to change my workflow for a system. The systems have to respect our workflow.

I'm against forcing each pull request into one commit. Each commit should be a logical unit of work. If a pull request (e.g. a new feature) contains a lot of changes, it sure can contain multiple commits.

**Comment by physikerwelt** [comment] 2013-10-21 11:02
Adjusting workflows to systems seems to be wrong approach in general.
The traceable git-history is written in terms of commits.
Pull requests are specific to github and hard to trace via git log. That's an argument for stable commits.

However, most important for me, is that there is stable master branch.
It would be nice if there would be way to navigate through the former stable state in order to trace problems.
Maybe fine grained version tags would be a good idea.

**Comment by aljoscha** [comment] 2013-10-21 12:31
I must admit that that I have also managed to create a broken commit now and then. In general, though, I think it is nice to have every commit be a working commit.

I do also realise however that right now it is the wild west out there. We are frantically fixing bugs and cranking out commits, so, I don't know ... :smile_cat:

**Comment by physikerwelt** [comment] 2013-10-21 13:03
As far as I have understood there is only one major difference between  gerrit/jenkins workflow and github/travis:
In gerrit/jenkins commits can be merged, if they pass the specified tests. Travis seems to check the commits/pull requests after they were merged.
For the github workflow the commits seem to be atomic. In gerrit you change your commit until it passes all tests. That way it glorifies the history;-)
However, beside the pre/post checking the systems are equal except for isomorphism:
commit <-> pull request
patch set <-> commit

**Comment by rmetzger** [comment] 2013-10-21 14:52
I had a little conversation with @physikerwelt and we resolved the issue.

We won't change the current development process, so that new contributors are not discouraged to help. But we advise everyone to commit only stable code.

**Closed as completed by rmetzger** 2013-10-21 14:52 UTC
