### ISSUE TITLE
Debian package creator has references to old config files

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#341] opened 2013-12-13 15:09 UTC
The "postinst" file in "stratosphere-dist/src/deb/control" still references "pact-user.xml"

**Comment by rmetzger** [comment] 2014-01-17 14:48
```
root@precise64:/etc/apt/sources.list.d# apt-get install stratosphere-dist
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  stratosphere-dist
0 upgraded, 1 newly installed, 0 to remove and 152 not upgraded.
Need to get 55.5 MB of archives.
After this operation, 62.2 MB of additional disk space will be used.
Get:1 http://dev.stratosphere.eu/apt/ ./ stratosphere-dist 0.2 [55.5 MB]
Fetched 55.5 MB in 12s (4,363 kB/s)                                                                                                                                                                               
Selecting previously unselected package stratosphere-dist.
(Reading database ... 54604 files and directories currently installed.)
Unpacking stratosphere-dist (from .../stratosphere-dist_0.2_all.deb) ...
Processing triggers for ureadahead ...
Setting up stratosphere-dist (0.2) ...
sed: can't read /usr/share/stratosphere-dist/conf/pact-user.xml: No such file or directory
dpkg: error processing stratosphere-dist (--configure):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 stratosphere-dist
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Is there a Debian/Ubuntu user who's willing to fix this?

**Comment by rmetzger** [comment] 2014-02-06 07:55
duplicate of https://github.com/stratosphere/stratosphere/issues/247

**Closed as completed by rmetzger** 2014-02-06 07:55 UTC
