### ISSUE TITLE
Scala quickstart problem

### ISSUE THREAD

**Issue by payberah** [stratosphere/stratosphere#384] opened 2014-01-09 07:17 UTC
Hi,

I have a problem on running the jar file in scala quickstart. The jar file was built without any problem, but when I want to run it, I get the following error:

.../stratosphere/bin$ ./stratosphere run -j ../stratosphere-project-0.1-SNAPSHOT.jar -a 1 file:///<path>/hamlet.txt file:///<path>/output

ERROR: No plan assembler class defined in manifest
eu.stratosphere.client.program.ProgramInvocationException: No plan assembler class defined in manifest
    at eu.stratosphere.client.program.PackagedProgram.getPactAssemblerFromJar(PackagedProgram.java:260)
    at eu.stratosphere.client.program.PackagedProgram.<init>(PackagedProgram.java:87)
    at eu.stratosphere.client.CliFrontend.run(CliFrontend.java:280)
    at eu.stratosphere.client.CliFrontend.parseParameters(CliFrontend.java:763)
    at eu.stratosphere.client.CliFrontend.main(CliFrontend.java:786)

Do you have any idea about this problem?

Thanks,
-- Amir

**Comment by aljoscha** [comment] 2014-01-09 07:24
Could you check whether the class name of you assembler class matches the namen given in pom.xml? It looks like this:

``` xml
<Pact-Assembler-Class>eu.stratosphere.quickstart.Job</Pact-Assembler-Class>
```

If you changed the package name or anything from the default it will not find it anymore.

**Comment by rmetzger** [comment] 2014-01-09 07:28
@aljoscha I recently changed something on the quickstarts.
The old quickstarts had a hardcoded artifactId (so we ignored the user input, if the user entered a custom artifactId).
It is now `<groupId>${groupId}</groupId>` and `<artifactId>${artifactId}</artifactId>`.
I think we have to use the `${package}` for the Pact-Assembler-Class manifest entry.

**Comment by rmetzger** [comment] 2014-01-09 07:31
@payberah: a quick fix for you would be to define the `-c` (or `--class`) argument for the `./stratosphere` client.
Something like this:

```
.../stratosphere/bin$ ./stratosphere run -j ../stratosphere-project-0.1-SNAPSHOT.jar -c eu.stratosphere.quickstart.Job -a 1 file:////hamlet.txt file:////output
```

Did you use the `curl .../quickstart-scala.sh | bash` thing to create the project?

**Comment by payberah** [comment] 2014-01-09 07:39
Thanks for your prompt replies. I tried your solution, but non of them worked. 

Yes, I used the "curl ..." to create the project.

Moreover, when I used "-c eu.stratosphere.quickstart.Job" in the command, I got the following error message instead:

ERROR: An unknown problem ocurred during the instantiation of the program assembler: java.lang.NoClassDefFoundError: eu/stratosphere/pact/common/plan/PlanAssemblerDescription
eu.stratosphere.client.program.ProgramInvocationException: An unknown problem ocurred during the instantiation of the program assembler: java.lang.NoClassDefFoundError: eu/stratosphere/pact/common/plan/PlanAssemblerDescription
    at eu.stratosphere.client.program.PackagedProgram.getPactAssemblerFromJar(PackagedProgram.java:287)
    at eu.stratosphere.client.program.PackagedProgram.<init>(PackagedProgram.java:117)
    at eu.stratosphere.client.CliFrontend.run(CliFrontend.java:282)
    at eu.stratosphere.client.CliFrontend.parseParameters(CliFrontend.java:763)
    at eu.stratosphere.client.CliFrontend.main(CliFrontend.java:786)
Caused by: java.lang.NoClassDefFoundError: eu/stratosphere/pact/common/plan/PlanAssemblerDescription
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:270)
    at eu.stratosphere.client.program.PackagedProgram.getPactAssemblerFromJar(PackagedProgram.java:276)
    ... 4 more
Caused by: java.lang.ClassNotFoundException: eu.stratosphere.pact.common.plan.PlanAssemblerDescription
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
    ... 17 more

**Comment by rmetzger** [comment] 2014-01-09 08:07
Okay, sorry for the inconveniences. We recently renamed many parts of the project.
It looks like the version you got from the quickstart script is not compatible with the Stratosphere version you installed.
More precisely, you probably installed a 0.4-rc1 or the 0.4 version and the archetype probably expects 0.4-SNAPSHOT.

Old api: 0.4-SNAPSHOT, 0.2
new api. 0.4-rc1, 0.4

You should certainly use the new api, we hope to release the stable 0.4 this week.
I'm going to rework the Scala quickstart now. I'll post you here once I done (the only problem is that my car is broken and I'm currently waiting for some guy who's coming to fix it .. this could cause some delay.)

**Comment by StephanEwen** [comment] 2014-01-09 08:12
Okay, there are some versions mixed here  (a 0.4 code version with a
pre-0.4 quickstart). Seems the quickstart is out of sync with the pending
release version. We will fix that asap and ping you back.

As a manual workaround, you could directly reference the version 0.4-rc1 or
0.5-SNAPSHOT in your project.
Am 09.01.2014 08:39 schrieb "payberah" notifications@github.com:

**Comment by rmetzger** [comment] 2014-01-09 08:44
Okay, things got clearer for me.
The `quickstart-scala.sh` version was pointing to the wrong version (0.4-SNAPSHOT). I fixed this now.
So the exception that @payberah currently has should be fixed.
But there is another issue with the scala quickstart that will prevent you from running it: https://github.com/stratosphere/stratosphere-quickstart/issues/6

Again, I'm really sorry that all this happened to you. 
Once Stratosphere and your projects are set up, things run smoothly. 
We will create scripts to automatically verify the quickstarts to avoid those problems in the future.

I will write again here if the last issue with the scala quickstart has been fixed. Should be within the next 4 hours.

**Comment by payberah** [comment] 2014-01-09 10:51
Thanks again, and looking forward to seeing the stable version.

**Comment by rmetzger** [comment] 2014-01-09 14:58
Okay, here's a personalized getting started for you ;)
The problem is that we don't have any "up to date" versions of the 0.4 release in maven central for you.
But since you want to develop an application for stratosphere, you need to have a stable code basis.

The following instructions help you to set up the 0.5-SNAPSHOT version. It contains everything you need and is in sync with maven central.
once the 0.4 release is out, the move back is quite easy for you (you only have to change the version in the `pom.xml`).

``` bash
# download latest 0.5 version:
wget http://stratosphere-bin.s3-website-us-east-1.amazonaws.com/stratosphere-0.5-SNAPSHOT.tgz
tar xzf stratosphere-0.5-SNAPSHOT.tgz
cd stratosphere
./bin/start-local.sh
# test everything with wordcount
wget -O hamlet.txt http://www.gutenberg.org/cache/epub/1787/pg1787.txt
bin/stratosphere run  --jarfile ./examples/stratosphere-java-examples-0.5-SNAPSHOT-WordCount.jar  --arguments 1 file://`pwd`/hamlet.txt file://`pwd`/wordcount-result.txt
# now we create your project
cd ..
curl https://raw2.github.com/stratosphere/stratosphere-quickstart/master/quickstart-scala-SNAPSHOT.sh | bash
cd quickstart
# you can import the contents of this directory into eclipse or intellj (as a maven project!)
# build jar file
mvn package
cd ..
cd stratosphere
# finally execute it
bin/stratosphere run  --jarfile ../quickstart/target/quickstart-0.1.jar  --arguments 1 file://`pwd`/hamlet.txt file://`pwd`/wordcount-result.txt 
```

All these issues will be resolved once the 0.4 release is out.
The problem is that the 0.4-rc1 release that is available in maven central is kind of broken

Please keep posting issues if you have any troubles using our system. We are very happy about every comment and feedback!

**Comment by payberah** [comment] 2014-01-09 15:09
Perfect! Everything worked well.

**Comment by aljoscha** [comment] 2014-01-14 12:41
Can we close this issue?

**Closed as completed** 2014-01-14 12:42 UTC
