### ISSUE TITLE
pact-compiler depends on pact-examples

### ISSUE THREAD

**Issue by sscdotopen** [stratosphere/stratosphere#36] opened 2013-06-14 09:30 UTC
In a layered architecture, you must only depend on layers below. Running into problems when modifying the examples code because of this wrong dependency.

**Comment by aalexandrov** [comment] 2013-06-22 04:19
I'm not sure whether this is a real issue. The dependency is defined only for the `test` scope and is caused by the use of some `eu.stratosphere.pact.example.*` classes located in `pact-examples` from the `eu.stratosphere.pact.compiler` test classes. 

If we want to have a coherent set of regression jobs to be used across different modules (e.g. for `pact-compiler` and `pact4s`), it makes sense to keep them in a separate package.

Alternatively, we can also make a hard copy of the `eu.stratosphere.pact.example` code under `eu.stratosphere.pact.compiler.examples` and resolve the dependency via code duplication.

**Comment by StephanEwen** [comment] 2013-07-03 01:47
I split the compiler tests into unit-style tests (isolated compiler behavior) and regression tests (full programs, including checks that reasonable plans are chosen). The later are in an individual project now (pact-compiler-tests) and depend on the examples package.

The pact compiler project itself has no more dependency on the pact-examples.

Fixed in cf90104cdad1760b594c3ffd7298ab49253d5e2e

**Closed as completed by StephanEwen** 2013-07-03 01:47 UTC
Labels: bug
