### ISSUE TITLE
Inconsistent information on the web site about Hadoop dependency

### ISSUE THREAD

**Issue by nullusDefectus** [stratosphere/stratosphere#513] opened 2014-02-26 14:09 UTC
The FAQ says Stratosphere does not depend on Hadoop, but the Downloads page says "Stratosphere has dependencies to Hadoop". Which of the two statements is true?
## FAQ

![image](https://f.cloud.github.com/assets/6477490/2270528/b8c9a93e-9eee-11e3-8413-5b086e163b80.png)
## Downloads

![image](https://f.cloud.github.com/assets/6477490/2270560/2dde8758-9eef-11e3-8fb6-578bec64aac2.png)

**Comment by StephanEwen** [comment] 2014-02-26 14:24
The Stratosphere system does in its core not depend on Hadoop. It can run on infrastructures where Hadoop is not installed.

A very common use case, however, is to analyze data that is stored in Hadoop's distributed file system (HDFS). To access HDFS files, you need the Hadoop client library that communicates with the distributed filesystem's servers. For that reason, we package this client with Stratosphere to make it work with HDFS files out of the box, and thus have a dependency to that client part of Hadoop. It is actually possible create a Stratosphere build with no Hadoop dependency. That one would then not be able to read HDFS files, but only local files, S3 files, or JDBC supported databases.

**Comment by StephanEwen** [comment] 2014-02-26 14:29
Addendum:
- Hadoop code is in the above case only ever active when you read an HDFS file.
- We have a special mode where the System uses Hadoop's scheduling framework (YARN). Like with HDFS files, this is not part of the core and is an optional mode of operation for people whose cluster uses that framework, to make Stratosphere easier to use in such setups.

Summary: It can work absolutely independent of Hadoop and the core does. We package Hadoop dependencies to ease the interplay with existing Hadoop infrastructure.

**Comment by nullusDefectus** [comment] 2014-02-26 14:40
Thanks for the explanation Stephan.

I guess, my original question still remains: Which of the two statements on the web site is true? It seems at least one of the two web pages (FAQ, Downloads) needs revision.

From your explanation, it looks like I _must_ have Hadoop installed even if I don't plan to use HDFS, and that (at least as of now) users need to build Stratosphere on their own to eliminate that dependency. Is my understanding correct? If it is, are there instructions on how users go about doing that?

Candidly, given the statement "Stratosphere is an alternative analysis engine to Hadoop's MapReduce" on the web site, it is a bit surprising/disappointing there is no Hadoop-independent build ready to download.

I hope my candid comments are appreciated.

**Comment by uce** [comment] 2014-02-26 14:52
Yes, your comments are appreciated. Thank you! :+1:

You don't need to have Hadoop installed. When building Stratosphere on your own, Maven takes care of downloading the Hadoop dependency for compilation etc. And if you just use the local filesytem (e.g. `file:///path/to/your/data`), no Hadoop dependent code will be executed. So it should be OK to just download the build for Hadoop 1 and use it locally.

Does this help?

We should think about clarifying the linked pages to avoid future confusion.

**Comment by nullusDefectus** [comment] 2014-02-26 15:46
I completely agree that the info on the web site needs be clearer. In the interest of adding to solutions (not just to problems), here are a couple of suggestions for the Downloads page:
1. The current button captions in the 'Hadoop 2 (YARN)' are confusing. If the choices here are about YARN regardless of Hadoop 1 and Hadoop 2, change the tab text to 'Hadoop YARN' and the button captions to 'Stratosphere (Hadoop 1 YARN)' and 'Stratosphere (Hadoop 2 YARN)'.  
2. Revise the text of the tab 'Hadoop 1' to 'No Hadoop or No YARN' and change the button caption to 'Stratosphere'
3. Remove the word 'Download' from the buttons.
4. Re-order the tabs to emphasize that Stratosphere can be used without Hadoop. I feel the Hadoop-independence angle should be front and center so more users are encouraged to try the system.
5. Revise the introductory text to something simple like "Download a Stratosphere build that meets your requirement". Alternatively, use a longer version such as:

Download a Stratosphere build that meets your requirement: Choose 'No Hadoop or No YARN' if you want to use Stratosphere independent of Hadoop or use it with Hadoop, but no YARN. Choose 'Hadoop YARN' if you want to use Stratosphere with Hadoop YARN.

**Comment by StephanEwen** [comment] 2014-02-26 16:24
Thanks for the comments, I see how that is a bit confusing right now.

If you do not have Hadoop installed, you can download any of the Hadoop 1 or Hadoop 2 versions, they will always work. They contain the same Stratosphere. The part that is different between these two versions is the code that reads from the Hadoop file system. If you do not use the Hadoop file system, this code is never active, so it does not matter which variant you have. Think of it as "Hadoop 1 enabled" and "Hadoop 2 enabled".

In all downloads, the Hadoop client is shipped with Stratosphere, but that does not mean an installation of Hadoop is required. As Ufuk said, the other inputs (like local files or S3) work totally without an installation of Hadoop. The system only has the optional possibility to read from HDFS.

Concerning YARN: YARN was introduced with Hadoop 2, so there is no YARN fro Hadoop 1. Also, Hadoop2 itself is built completely on top of YARN, to there is also no Hadoop 2 version without YARN.

**Comment by nullusDefectus** [comment] 2014-02-26 22:52
Thanks StephanEwen for your patient explanation.

I hope we can all agree that if it takes this long a thread to clarify something on the web site, the web site probably needs a revision. :)

I love your phrase "Hadoop Enabled". It aptly captures what I now understand is going on. 

The bottom line is that the current introductory text under "Ready To Run Package" is incorrect in saying "Stratosphere has dependencies to Hadoop". Further, the tab text and the button captions are misleading. For example, the first tab's text reads "Hadoop 2 (YARN)", but the tab has two download options: one qualified with YARN; another unqualified. I am _guessing_ the qualified option is to use Stratosphere and Hadoop 2 with just YARN, but no HDFS; and the unqualified option is use Stratosphere and Hadoop 2 with HDFS.

Here are my new suggestions on the revisions that could be made:
1. Revise tab text to "Hadoop 1" and "Hadoop 2".
2. In the "Hadoop 1" tab, revise button text to "Stratosphere (No Hadoop or Hadoop 1)"
3. In the "Hadoop 2" tab, revise button text to "Stratosphere (Hadoop 2)" and "Stratosphere (only Hadoop 2 YARN)"
   -- I am not sure if this is the intended separation. 
4. Re-order the tabs/buttons to show the "No Hadoop" option first to emphasize that Stratosphere can be used without Hadoop. 
5. I prefer seeing a button "No Hadoop" in the "Hadoop 1" tab, which simply downloads the same thing as "Hadoop 1". If used, this button should be first in the tab.
6. The tabs are unnecessary: Instead, directly add three buttons "No Hadoop or Hadoop 1", "Hadoop 2", and "Hadoop 2 (only YARN). Even in this approach, it is better to have a separate "No Hadoop" button.
7. Revise the introductory text to something like:

"Stratosphere has no run-time dependencies to Hadoop, but it is "Hadoop Enabled" by binding it to the Hadoop client. The binding is used only if you use a Hadoop feature with Stratosphere. So, you do not need to install Hadoop if you do not use any Hadoop feature"

Finally, a note why I am spending so much time fussing about problems and volunteering revisions: 
1. I like to develop a mental model of things I use before using them.
2. I am a "quality junkie" and like to help improve anything I encounter so everyone benefits. Providing+accepting feedback is the first step to improvement. 
3. I dig the Hadoop-independence promised on the Stratosphere home page. I'd rather spend time making sure that the independence is real than accepting it and spending time later in a rabbit hole installing several dependencies. 
4. I don't want to just point out problems. Instead, I want to be part of the solution.

**Comment by uce** [comment] 2014-02-26 23:50
Thank you for the feedback! I agree with a revision of the text, but technically _"Stratosphere has dependencies to Hadoop"_ is correct, because of the HDFS client. As your revision text captures aptly, the core of the problem is not the dependency but the following: the current text sounds like you **need** to have Hadoop installed to run Stratosphere. This should be adressed with a revised text.

But I disagree with providing a Stratosphere-without-Hadoop version. First of all it doesn't hurt anyone, who doesn't use it -- at the same time a lot of people will indeed use it (in real distributed setups).

YARN and HDFS are not mutually exclusive. Check this document for details: http://hortonworks.com/hadoop/yarn/. The first Hadoop 2 download is the Stratosphere distribution compiled with Hadoop 2 for the HDFS client. The right Hadoop 2 download is an executable JAR, which allows you to execute Stratosphere on your YARN cluster. Details are here: http://stratosphere.eu/docs/0.4/setup/yarn.html.

**Comment by nullusDefectus** [comment] 2014-02-27 02:34
uce: I agree "Stratosphere has dependencies to Hadoop" is correct because of the HDFS client. Hopefully revising the text (including fixing the inconsistency in the FAQ) will clarify things for a prospective user.

I understand your position of not providing a "No Hadoop" version, though I am not convinced by the first part of your reason for it. However, it seems you are implying it is possible to build Stratosphere without the HDFS client dependency. _If so_, the technical correctness of the statement "Stratosphere has dependencies to Hadoop" is somewhat self-fulfilling in that Stratosphere depends on HDFS client because it is bound to the HDFS client for reasons other than Stratosphere needing that binding. (However, not having looked at the code, I have a feeling the binding might be necessary due to Stratosphere referencing an HDFS Java interface, maybe even using that interface to access the local file system.)

I do notice an error on my part when I wrote earlier "only YARN; no HDFS". I meant to write "only HDFS; no YARN". Regardless, I understand you are now clarifying that the two Hadoop 2 releases of Stratosphere are one for use with HDFS and another for use with YARN. If so, it seems it will be helpful to the prospective user to get this clarification up front.

Thank you all again for engaging me. At this point, I will suspend this conversation so I don't take up any more of your time. I look forward to reading the revised Documentation and Download pages, and hope a working VM image will soon be available so I can try the system.

**Comment by StephanEwen** [comment] 2014-02-28 17:50
Thank you, that is very good input!

We will update the description on the website in the next days. Can we ping you after that to get you opinion on whether the changes made it more clear?

**Comment by nullusDefectus** [comment] 2014-02-28 19:13
Sure, please ping me.

**Comment by rmetzger** [comment] 2014-03-04 12:30
Okay, we updated the website.

**Comment by MoeweX** [comment] 2014-04-16 20:19
Is there still something to do @rmetzger ? Otherwise we can close this issue ... :).

**Closed as completed** 2014-04-18 18:24 UTC
Labels: enhancement, website
