### ISSUE TITLE
inputsplits organization 

### ISSUE THREAD

**Issue by kfleischmann** [stratosphere/stratosphere#742] opened 2014-04-30 12:05 UTC
Hey guys. there is a issue concerning the organization of the input splits. As far as i understood there is a blocking part  (log-server?) inside the code.
So
1. what is actually blocking?
2. what code is blocking?

**Comment by StephanEwen** [comment] 2014-04-30 12:20
Sorry, I don't quite understand what the issue is.

Can you give us a bit more context? ;-)

**Comment by kfleischmann** [comment] 2014-04-30 12:28
i have not that much context. My information right now is that there is an issue in that direction.

Calling "InputSplitAssigner::getNextInputSplit(final ExecutionVertex vertex) " results in a communication with an "log-server" which organizes the splitting for the tasks. So this "log-Server" communication could be a bottleneck if many tasks are running with many splits.

**Comment by rmetzger** [comment] 2014-04-30 15:33
In a typical HDFS setup, there is a central NameNode that maintains the locations of a file's blocks. I don't know anything about a "log-server".
You might want to do some experiments with a HDFS setup to see if there is really a bottleneck.
I think it would be great if you could take a look into that.

**Comment by StephanEwen** [comment] 2014-04-30 15:48
On the NameNode, the InputSplitAssigner is responsible for the assignment.

I think in the current design, there has to be a single point of assignment
in some way, but it can be improved to make it as little a bottleneck as
possible.

**Comment by fhueske** [comment] 2014-04-30 21:43
I think the code you are referring to is:
- [InputSplitManager](https://github.com/stratosphere/stratosphere/blob/0572f4f3983ea4bd6b859f1dba65c7e0252ca10d/stratosphere-runtime/src/main/java/eu/stratosphere/nephele/jobmanager/splitassigner/InputSplitManager.java)
- [InputSplitTracker](https://github.com/stratosphere/stratosphere/blob/0572f4f3983ea4bd6b859f1dba65c7e0252ca10d/stratosphere-runtime/src/main/java/eu/stratosphere/nephele/jobmanager/splitassigner/InputSplitTracker.java)

The ISManager calles the ISTracker (l. 176) to check if an input split needs to be reassigned (in case of a task failure). The ISTracker looks up assigned input splits in an `inputSplitLog` in a `sychronized` block.
However, the `inputSplitLog` is a local `List` object (one for each task instance / ExecutionVertex) and part of the JobManager and not a server. I don't think that this would cause significant delays when assigning input splits.
@kfleischmann Why did this particular part of the code raise your attention? If it is causing an actual problem for you, can you give a bit more background about the splits and job that you are running? Number of input splits, small or large splits, type of input splits, parallelism of job, etc. 

My intuition is that this code is not longer required and could be removed. But this should be checked more throughly.

**Comment by kfleischmann** [comment] 2014-07-01 16:05
Is it correct that the input-splits are assigned to be local (minimal-distance) during the runtime?  Or is there an optimization step during scheduling phase?

**Comment by StephanEwen** [comment] 2014-07-01 16:07
It is runtime only. It it not taken into account during scheduling (which
would be desirable).

**Comment by fhueske** [comment] 2014-07-02 08:54
Hi, the Stratosphere issues have been imported into the Apache Flink JIRA.
--> https://issues.apache.org/jira/browse/FLINK-742
Please continue the discussion over there :-)

**Closed as completed by fhueske** 2014-07-02 08:54 UTC
