### ISSUE TITLE
Strange (and faulty) Iterations Behaviour

### ISSUE THREAD

**Issue by aljoscha** [stratosphere/stratosphere#123] opened 2013-10-03 07:16 UTC
In KMeansIterative, when you add an identity mapper after the reduceClusterCenter reducer you get:
java.lang.RuntimeException: : BUG: The task must have at least one output
    at eu.stratosphere.pact.runtime.task.RegularPactTask.registerInputOutput(RegularPactTask.java:248)
    at eu.stratosphere.nephele.execution.RuntimeEnvironment.<init>(RuntimeEnvironment.java:194)
    at eu.stratosphere.nephele.executiongraph.ExecutionGroupVertex.<init>(ExecutionGroupVertex.java:237)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.createVertex(ExecutionGraph.java:497)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.constructExecutionGraph(ExecutionGraph.java:275)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.<init>(ExecutionGraph.java:176)
    at eu.stratosphere.nephele.jobmanager.JobManager.submitJob(JobManager.java:532)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at eu.stratosphere.nephele.ipc.RPC$Server.call(RPC.java:417)
    at eu.stratosphere.nephele.ipc.Server$Handler.run(Server.java:946)
I discovered this one from a plan in the scala frontend where I also have a final mapper that does some real work after a reducer in an iteration (BulkIteration).

**Comment by sscdotopen** [comment] 2013-10-03 07:38
I suggest you open another issue for the second error as it seems to be a different thing. Could you also add a stacktrace from one of the machines for the case where you saw the stalling? I've seen stalling two, it can either be caused by deadlocks in the network layer or by the compiler failing to insert dams at the correct points.

**Comment by aljoscha** [comment] 2013-10-08 15:00
@StephanEwen I have added a failing test case in https://github.com/aljoscha/ozone/tree/chained-mapper-bug

**Comment by StephanEwen** [comment] 2013-10-21 09:27
Fixed in eec2840d831637e05a55a16bdd5a3e039a7d1ce0

**Closed as completed by StephanEwen** 2013-10-21 09:27 UTC
Labels: bug

**Comment by aljoscha** [comment] 2013-10-21 12:27
So it just does not chain them, the mapper is a separate operator for now?

**Comment by StephanEwen** [comment] 2013-10-21 12:38
The last operator in an iteration must always be separate now, because the runtime uses the main operator's output collector (and config parameters) for the back channel.

@uce Is reworking the tail tasks anyways, I would suggest to include a proper fix in the reworkings there.

We should actually rework the chaining idea into something more elaborate, such that we have proper trees of operators inside a vertex, not just this poor-mans-version in form of the push chain.
